#!/usr/bin/env bash
set -eo pipefail; [[ $PLUSHU_TRACE ]] && set -x

if [[ -d "$PLUSHU_ROOT/plugins/nginx" ]]; then
  echo "include $PLUSHU_ROOT/apps/*/nginx.conf;" \
    >"$PLUSHU_ROOT/nginx.conf.d/apps.conf"

  cat > "$PLUSHU_ROOT/nginx.conf.d/ssl.conf" <<EOF
ssl_session_cache shared:SSL:20m;
ssl_session_timeout 10m;

ssl_ciphers EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;
ssl_protocols TLSv1.2 TLSv1.1 TLSv1;
ssl_prefer_server_ciphers on;
EOF

else
  echo "This plugin depends on the plushu/plushu-nginx plugin."
  echo "Please install that dependency, then reinstall this plugin:"
  echo
  echo "# plushu install nginx"
  echo "# plushu reinstall nginx-app-vhosts"
fi
