#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

if [[ -d "$PLUSHU_ROOT/plugins/nginx" ]]; then
  printf '%s\n' "include http/apps/*/*.conf;" \
    >"$PLUSHU_ROOT/nginx/http/apps.conf"

  # Write some sensible SSL configuration directives
  if [[ ! -f "$PLUSHU_ROOT/nginx/http/ssl.conf" ]]; then
    cat > "$PLUSHU_ROOT/nginx/http/ssl.conf" <<EOF
ssl_session_cache shared:SSL:20m;
ssl_session_timeout 10m;

ssl_ciphers EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;
ssl_protocols TLSv1.2 TLSv1.1 TLSv1;
ssl_prefer_server_ciphers on;
EOF
  fi
else
  echo "This plugin depends on the plushu/plushu-nginx plugin."
  echo "Please install that dependency, then reinstall this plugin:"
  echo
  echo "# plushu install nginx"
  echo "# plushu reinstall nginx-app-vhosts"
fi
